<a href="https://colab.research.google.com/github/cmd0850/machine_lerning/blob/main/%D0%94%D0%B6%D0%B5%D0%BD%D1%87%D0%B0%D0%BA%D0%BE_3_10_%D1%80%D0%BE%D0%B1%D0%BE%D1%82%D0%B0_%D0%B7_%D0%BC%D0%B0%D1%82%D1%80%D0%B8%D1%86%D1%8F%D0%BC%D0%B8.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Тренувальний ноутбук: вектори, матриці та функції

Мета роботи — закріпити навички роботи з **NumPy**: створення та перетворення векторів і матриць, виконання арифметичних і лінійно-алгебраїчних операцій, використання математичних функцій та написання власних функцій.

### Правила виконання
- Виконуйте завдання послідовно.
- Для обчислень використовуйте `numpy`.
- Результати виводьте за допомогою `print()` або просто залишайте змінну останнім рядком комірки.
- Не змінюйте початкові дані, якщо це прямо не зазначено в умові.


## Підготовка

In [2]:
import numpy as np

np.set_printoptions(precision=3, suppress=True)


## Завдання 1. Створення векторів

1. Створіть вектор `a`, що містить числа від 1 до 10.
2. Створіть вектор `b` з 10 рівновіддалених значень від 0 до 1.
3. Виведіть обидва вектори та їх розмір.

In [9]:
# Ваш код тут

a=np.arange(1,11)
print(a, a.size)
b=np.linspace(0,1,10)
print(b, b.size)

[ 1  2  3  4  5  6  7  8  9 10] 10
[0.    0.111 0.222 0.333 0.444 0.556 0.667 0.778 0.889 1.   ] 10


## Завдання 2. Арифметичні дії з векторами

Нехай задано:

`x = [2, 4, 6, 8, 10]`  
`y = [1, 3, 5, 7, 9]`

Обчисліть:
- суму `x + y`;
- різницю `x - y`;
- поелементний добуток;
- поелементне ділення;
- квадрат кожного елемента вектора `x`.

In [11]:
x = np.array([2, 4, 6, 8, 10])
y = np.array([1, 3, 5, 7, 9])

# Ваш код тут
print(x+y)
print(x-y)
print(x*y)
print(x/y)
print(x**2)

[ 3  7 11 15 19]
[1 1 1 1 1]
[ 2 12 30 56 90]
[2.    1.333 1.2   1.143 1.111]
[  4  16  36  64 100]


## Завдання 3. Скалярний добуток і норма вектора

Для векторів `u = [3, -1, 2]` та `v = [1, 4, -2]`:

1. Обчисліть скалярний добуток.
2. Знайдіть евклідову норму кожного вектора.
3. Обчисліть косинус кута між векторами за формулою

\[
\cos(\alpha)=\frac{u\cdot v}{\|u\|\|v\|}
\]


In [14]:
u = np.array([3, -1, 2])
v = np.array([1, 4, -2])

# Ваш код тут
print(np.dot(u, v))
print(np.linalg.norm(u))
print(np.linalg.norm(v))
print(np.dot(u,v)/(np.linalg.norm(u)*np.linalg.norm(v)))


-5
3.7416573867739413
4.58257569495584
-0.2916059217599022


## Завдання 4. Індексація та логічні умови

Створіть вектор із чисел від `-10` до `10`.

За допомогою індексації та логічних масок:
- виберіть усі додатні елементи;
- виберіть усі парні елементи;
- замініть усі від'ємні значення на `0`;
- знайдіть кількість елементів, більших за `5`.

In [17]:
arr = np.arange(-10, 11)

# Ваш код тут

print(arr[arr>0])
print(arr[arr%2==0])
arr[arr<0]=0
print(arr)
print(np.sum(arr>5))

[ 1  2  3  4  5  6  7  8  9 10]
[-10  -8  -6  -4  -2   0   2   4   6   8  10]
[ 0  0  0  0  0  0  0  0  0  0  0  1  2  3  4  5  6  7  8  9 10]
5


## Завдання 5. Створення матриць

Створіть:

1. Матрицю `A` розміру `3 × 3`, що містить числа від 1 до 9.
2. Нульову матрицю `3 × 4`.
3. Одиничну матрицю `4 × 4`.
4. Матрицю `2 × 5`, заповнену числом `7`.

Виведіть усі матриці.

In [27]:
# Ваш код тут
mat=np.arange(1,10).reshape(3,3)
print(mat)

print(np.zeros((3,3)))
print(np.ones((3,3)))
print(np.full((2,5),7))

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
[[7 7 7 7 7]
 [7 7 7 7 7]]


## Завдання 6. Доступ до елементів матриці

Для матриці

\[
M =
\begin{bmatrix}
5 & 2 & 7 & 1\\
3 & 8 & 4 & 6\\
9 & 0 & 2 & 5
\end{bmatrix}
\]

виконайте:
- отримайте другий рядок;
- отримайте третій стовпець;
- отримайте підматрицю з перших двох рядків і останніх двох стовпців;
- знайдіть максимальний і мінімальний елементи.

In [39]:
matrix = np.array([
    [5, 2, 7, 1],
    [3, 8, 4, 6],
    [9, 0, 2, 5]
])

# Ваш код тут
print('другий ряд:', matrix[1])
print('тревтій стовп:', matrix[:,2])
print('підматриця:\n', matrix[:2,2:])
print(np.max(matrix), np.min(matrix))


другий ряд: [3 8 4 6]
тревтій стовп: [7 4 2]
підматриця:
 [[7 1]
 [4 6]]
9 0


## Завдання 7. Операції з матрицями

Нехай задано дві матриці:

\[
A =
\begin{bmatrix}
1 & 2\\
3 & 4
\end{bmatrix},
\quad
B =
\begin{bmatrix}
5 & 6\\
7 & 8
\end{bmatrix}
\]

Обчисліть:
- `A + B`;
- `A - B`;
- поелементний добуток;
- матричний добуток `A @ B`;
- транспоновану матрицю `A`.

In [43]:
a = np.array([[1, 2],
              [3, 4]])

b = np.array([[5, 6],
              [7, 8]])

# Ваш код тут

print(a+b)
print(a-b)
print(a*b)
print(a@b)
print(a.T)

[[ 6  8]
 [10 12]]
[[-4 -4]
 [-4 -4]]
[[ 5 12]
 [21 32]]
[[19 22]
 [43 50]]
[[1 3]
 [2 4]]


## Завдання 8. Визначник та обернена матриця

Для матриці

\[
A =
\begin{bmatrix}
4 & 7\\
2 & 6
\end{bmatrix}
\]

1. Знайдіть визначник.
2. Знайдіть обернену матрицю.
3. Перевірте результат множенням `A @ A_inv`.
4. Поясніть у коментарі, який результат має бути отриманий.

In [52]:
A = np.array([[4, 7],
              [2, 6]])

# Ваш код тут
print(np.linalg.det(A))
a_inv=np.linalg.inv(A)
print(a_inv)
print(A@a_inv) #повинна вийти одиинчна матриця

10.000000000000002
[[ 0.6 -0.7]
 [-0.2  0.4]]
[[ 1. -0.]
 [ 0.  1.]]


## Завдання 9. Розв'язання системи лінійних рівнянь

Розв'яжіть систему:

\[
\begin{cases}
2x + y = 5 \\
x - y = 1
\end{cases}
\]

Подайте коефіцієнти у вигляді матриці `A`, праву частину — вектора `b`, а потім використайте `np.linalg.solve()`.

In [54]:
# Ваш код тут
a=np.array([[2,1],[1,-1]])
b=np.array([5,1])
x=np.linalg.solve(a,b)
print(x)

[2. 1.]


## Завдання 10. Агрегувальні функції

Для матриці

```python
data = np.array([
    [10, 20, 30],
    [15, 25, 35],
    [12, 22, 32],
    [18, 28, 38]
])
```

знайдіть:
- суму всіх елементів;
- середнє значення;
- середнє по кожному стовпцю;
- суму по кожному рядку;
- стандартне відхилення;
- індекс максимального елемента в кожному рядку.

In [58]:
data = np.array([
    [10, 20, 30],
    [15, 25, 35],
    [12, 22, 32],
    [18, 28, 38]
])

# Ваш код тут
print(np.sum(data))
print(np.mean(data))
print(np.mean(data, axis=0))
print(np.sum(data, axis=1))
print(np.std(data))
print(np.argmax(data))

285
23.75
[13.75 23.75 33.75]
[60 75 66 84]
8.709429755538917
11


## Завдання 11. Математичні функції NumPy

Створіть вектор із 9 значень від `-2` до `2`.

Для кожного значення обчисліть:
- квадрат;
- модуль;
- експоненту `e^x`;
- синус;
- косинус.

Окремо створіть вектор із додатних значень і обчисліть для нього натуральний логарифм та квадратний корінь.

In [66]:
# Ваш код тут
v=np.linspace(-2,2, 9)
print(v)
print(np.shape(v))
print(v**2)
print(np.abs(v))
print(np.exp(v))
print(np.sin(v))
print(np.cos(v))

[-2.  -1.5 -1.  -0.5  0.   0.5  1.   1.5  2. ]
(9,)
[4.   2.25 1.   0.25 0.   0.25 1.   2.25 4.  ]
[2.  1.5 1.  0.5 0.  0.5 1.  1.5 2. ]
[0.135 0.223 0.368 0.607 1.    1.649 2.718 4.482 7.389]
[-0.909 -0.997 -0.841 -0.479  0.     0.479  0.841  0.997  0.909]
[-0.416  0.071  0.54   0.878  1.     0.878  0.54   0.071 -0.416]


## Завдання 12. Власна функція

Напишіть функцію `vector_stats(x)`, яка приймає числовий вектор і повертає:

- мінімум;
- максимум;
- середнє;
- медіану;
- стандартне відхилення.

Перевірте функцію на векторі:

`[4, 7, 1, 9, 3, 8, 5]`.

In [67]:
def vector_stats(x):
    print(np.min(x))
    print(np.max(x))
    print(np.mean(x))
    print(np.median(x))
    print(np.std(x))
    pass


# Перевірка функції
test_vector = np.array([4, 7, 1, 9, 3, 8, 5])
vector_stats(test_vector)


1
9
5.285714285714286
5.0
2.657296462534039


## Завдання 13. Функція з умовою

Створіть функцію

\[
f(x) =
\begin{cases}
x^2, & x < 0 \\
2x + 1, & x \geq 0
\end{cases}
\]

Застосуйте її до вектора значень від `-5` до `5`.

Спробуйте реалізувати функцію двома способами:
1. через звичайну функцію Python;
2. через `np.where()`.

In [73]:
x = np.arange(-5, 6)

# Варіант 1
def vector(m):
    for j in range(len(m)):
        if m[j]<0:
            m[j]=m[j]**2
        else:
            m[j]=2*m[j]+1
    return m
k=vector(x)
print(k)
# Варіант 2
x = np.arange(-5, 6)
x2=np.where(x<0, x**2, 2*x+1)
print(x2)


[25 16  9  4  1  1  3  5  7  9 11]
[25 16  9  4  1  1  3  5  7  9 11]


## Завдання 14. Робота з двовимірною функцією

Нехай

\[
f(x, y) = x^2 + 2y
\]

Задайте:

`x = [1, 2, 3]`  
`y = [10, 20, 30]`

1. Обчисліть значення функції поелементно.
2. Створіть усі можливі комбінації `x` та `y` за допомогою `np.meshgrid()`.
3. Обчисліть `f(x, y)` для кожної комбінації.

In [77]:
x = np.array([1, 2, 3])
y = np.array([10, 20, 30])

# Ваш код тут
f1=x**2+2*y
print(f1)

x2, y2=np.meshgrid(x, y)
print(x2, y2)
f2=x2**2+2*y2
print(f2)

[21 44 69]
[[1 2 3]
 [1 2 3]
 [1 2 3]] [[10 10 10]
 [20 20 20]
 [30 30 30]]
[[21 24 29]
 [41 44 49]
 [61 64 69]]


## Завдання 15. Підсумкове

Згенеруйте матрицю `5 × 5` із випадкових цілих чисел від `1` до `100`.

Виконайте такі дії:
1. Знайдіть середнє значення кожного рядка.
2. Знайдіть середнє значення кожного стовпця.
3. Замініть усі елементи, менші за загальне середнє матриці, на `0`.
4. Знайдіть рядок із найбільшою сумою.
5. Нормалізуйте початкову матрицю за формулою:

\[
x_{norm} = \frac{x - x_{min}}{x_{max} - x_{min}}
\]

6. Напишіть функцію, яка виконує таку нормалізацію для довільної числової матриці.

In [90]:
rng = np.random.default_rng(42)
matrix = rng.integers(1, 101, size=(5, 5))

print("Початкова матриця:")
print(matrix)
matrix2=matrix.copy()

# Ваш код тут
print(np.mean(matrix, axis=1))
print(np.mean(matrix, axis=0))
matrix[matrix<np.mean(matrix)]=0
print(matrix)
ma=np.sum(matrix, axis=1)
row=np.argmax(ma)
print(matrix[row])
norm = (matrix2 - np.min(matrix2)) / (np.max(matrix2) - np.min(matrix2))
print(norm)

def normal(matrix):
    matrix=np.array(matrix, dtype=float)
    m_min=np.min(matrix)
    m_max=np.max(matrix)
    return (matrix-m_min)/(m_max-m_min)

print(normal(matrix2))

Початкова матриця:
[[ 9 78 66 44 44]
 [86  9 70 21 10]
 [53 98 74 77 72]
 [79 52 13 84 46]
 [51 38 19 93 79]]
[48.2 39.2 74.8 54.8 56. ]
[55.6 55.  48.4 63.8 50.2]
[[ 0 78 66  0  0]
 [86  0 70  0  0]
 [ 0 98 74 77 72]
 [79  0  0 84  0]
 [ 0  0  0 93 79]]
[ 0 98 74 77 72]
[[0.    0.775 0.64  0.393 0.393]
 [0.865 0.    0.685 0.135 0.011]
 [0.494 1.    0.73  0.764 0.708]
 [0.787 0.483 0.045 0.843 0.416]
 [0.472 0.326 0.112 0.944 0.787]]
[[0.    0.775 0.64  0.393 0.393]
 [0.865 0.    0.685 0.135 0.011]
 [0.494 1.    0.73  0.764 0.708]
 [0.787 0.483 0.045 0.843 0.416]
 [0.472 0.326 0.112 0.944 0.787]]


## Короткий висновок

У 2–3 реченнях напишіть:
- які операції з векторами та матрицями були опрацьовані;
- які функції NumPy виявилися найкориснішими;
- що було найскладнішим у виконанні роботи.


In [ ]:
# За бажанням можна залишити висновок тут як текстовий рядок або коментар

