<a href="https://colab.research.google.com/github/cmd0850/machine_lerning/blob/main/%D0%9B%D0%A01_%D0%94%D0%B6%D0%B5%D0%BD%D1%87%D0%B0%D0%BA%D0%BE_3_10.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Лабораторна робота 1. NumPy

**Тема:** основи роботи з бібліотекою NumPy, масиви, вектори та матриці.

### Правила роботи
- Виконуйте завдання послідовно.
- Для обчислень використовуйте можливості **NumPy**.
- Не замінюйте операції NumPy звичайними Python-циклами, якщо це прямо не вказано в умові.
- Після виконання кожного завдання виводьте отриманий результат.


## 0. Підготовка середовища

### Завдання 0
Імпортуйте бібліотеку NumPy з псевдонімом `np`. Виведіть версію встановленої бібліотеки NumPy.

In [68]:
# Код студента
import numpy as np

print(np.version)

<module 'numpy.version' from '/usr/local/lib/python3.13/dist-packages/numpy/version.py'>


## 1. Створення масивів NumPy

### Завдання 1
Створіть одновимірний NumPy-масив із чисел:
`[2, 4, 6, 8, 10]`.

Виведіть масив та його тип за допомогою `type()`.

In [69]:
# Код студента
print(type(np.array([2, 4, 6, 8, 10])))

<class 'numpy.ndarray'>


### Завдання 2
Створіть:
1. масив із 10 нулів;
2. масив із 8 одиниць;
3. масив із 6 елементів, усі значення яких дорівнюють `7`.

Використайте відповідні функції NumPy.

In [72]:
# Код студента
print(np.zeros(10))
print(np.full(8,1))
print(np.full(6, 7))


[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[1 1 1 1 1 1 1 1]
[7 7 7 7 7 7]


### Завдання 3
Створіть масив цілих чисел від `1` до `20` включно.

Після цього створіть окремий масив парних чисел від `2` до `20`.

In [ ]:
# Код студента
arr=np.arange(1,21)
even_arr=np.arange(2,21,2)

print(arr)
print(even_arr)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
[ 2  4  6  8 10 12 14 16 18 20]


### Завдання 4
За допомогою `np.linspace()` створіть масив із **11 рівновіддалених чисел** від `0` до `1` включно.

In [ ]:
# Код студента
arr=np.linspace(0,1,11)

print(arr)

[0.  0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9 1. ]


### Завдання 5
Створіть матрицю розміром `3 × 4`, заповнену числами від `1` до `12`.

Спочатку створіть одновимірний масив, а потім змініть його форму.

In [ ]:
# Код студента
arr=np.arange(1,13)
matrix=arr.reshape(3,4)

matrix

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

## 2. Основні характеристики масивів

### Завдання 6
Для матриці, створеної у попередньому завданні, визначте та виведіть:
- кількість вимірів;
- форму;
- загальну кількість елементів;
- тип даних елементів.

Використайте атрибути `ndim`, `shape`, `size`, `dtype`.

In [ ]:
# Код студента
print("виміри:", np.ndim(matrix))
print("форма:", np.shape(matrix))
print('розмір:', np.size(matrix))
print('тип:', matrix.dtype)

виміри: 2
форма: (3, 4)
розмір: 12
тип: int64


### Завдання 7
Створіть масив:
`[1.2, 3.5, 5.7, 7.9]`.

Перетворіть його елементи на цілі числа за допомогою `astype()` та виведіть новий масив.

In [74]:
# Код студента
arr=np.array([1.2, 3.5, 5.7, 7.9])
arr.astype(int)

array([1, 3, 5, 7])

## 3. Індексація та зрізи

### Завдання 8
Створіть масив:
`[10, 20, 30, 40, 50, 60, 70, 80]`.

Виведіть:
1. перший елемент;
2. останній елемент;
3. елементи з індексами від `2` до `5` включно;
4. кожен другий елемент.

In [79]:
# Код студента
arr=np.array([10, 20, 30, 40, 50, 60, 70, 80])

print(arr[0])
print(arr[-1])
print(arr[2:5])
print(arr[1::2])

10
80
[30 40 50]
[20 40 60 80]


### Завдання 9
Створіть матрицю:

```text
[[ 1,  2,  3,  4],
 [ 5,  6,  7,  8],
 [ 9, 10, 11, 12]]
```

Виведіть:
1. елемент `7`;
2. другий рядок;
3. третій стовпець;
4. підматрицю з останніх двох рядків і перших двох стовпців.

In [ ]:
# Код студента
mat=np.array([[ 1,  2,  3,  4],
 [ 5,  6,  7,  8],
 [ 9, 10, 11, 12]])

print('елемент 7:', matrix[1,2])
print('другий ряд:', matrix[1])
print('тревтій стовп:', matrix[:,2])
print('підматриця:\n', matrix[1:,:2])


елемент 7 7
другий ряд [5 6 7 8]
третвй стовп [ 3  7 11]
підматриця
 [[ 5  6]
 [ 9 10]]


### Завдання 10
Створіть масив чисел від `1` до `15`.

Замініть усі елементи з індексами від `5` до `9` включно на число `0`.

In [ ]:
# Код студента
arr=np.arange(1,16)
arr[5:10]=0

arr

array([ 1,  2,  3,  4,  5,  0,  0,  0,  0,  0, 11, 12, 13, 14, 15])

## 4. Арифметичні операції та агрегатні функції

### Завдання 11
Створіть два масиви:

```python
a = [1, 2, 3, 4, 5]
b = [10, 20, 30, 40, 50]
```

Виконайте поелементно:
- додавання;
- віднімання;
- множення;
- ділення.

In [82]:
# Код студента

a = np.array([1, 2, 3, 4, 5])
b = np.array([10, 20, 30, 40, 50])

print(a+b)
print(a-b)
print(a*b)
print(a/b)

[11 22 33 44 55]
[ -9 -18 -27 -36 -45]
[ 10  40  90 160 250]
[0.1 0.1 0.1 0.1 0.1]


### Завдання 12
Для масиву:

`[4, 8, 15, 16, 23, 42]`

обчисліть:
- суму;
- середнє значення;
- мінімум;
- максимум;
- медіану;
- стандартне відхилення.

In [87]:
# Код студента
arr=np.array([4, 8, 15, 16, 23, 42])

print(np.sum(arr))
print(np.mean(arr))
print(np.min(arr))
print(np.max(arr))
print(np.median(arr))
print(np.std(arr))

108
18.0
4
42
15.5
12.315302134607444


### Завдання 13
Створіть матрицю:

```text
[[1, 2, 3],
 [4, 5, 6],
 [7, 8, 9]]
```

Обчисліть:
1. суму всіх елементів;
2. суму по кожному стовпцю;
3. суму по кожному рядку;
4. середнє значення по кожному стовпцю.

In [88]:
# Код студента
mat=np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]])

print('сума', np.sum(mat))
print('сума по стовпцях',np.sum(mat, axis=0))
print('по рядах',np.sum(mat, axis=1))
print('середне по стовпах',np.mean(mat, axis=0))

сума 45
сума по стовпцях [12 15 18]
по рядах [ 6 15 24]
середне по стовпах [4. 5. 6.]


### Завдання 14
Для масиву чисел від `1` до `10` обчисліть:
- квадрат кожного елемента;
- квадратний корінь кожного елемента;
- натуральний логарифм кожного елемента.

Використайте функції NumPy.

In [89]:
# Код студентa
arr=np.arange(1,11)

print('квадрат', np.square(arr))
print('корінь', np.sqrt(arr))
print('логарим', np.log(arr))

квадрат [  1   4   9  16  25  36  49  64  81 100]
корінь [1.         1.41421356 1.73205081 2.         2.23606798 2.44948974
 2.64575131 2.82842712 3.         3.16227766]
логарим [0.         0.69314718 1.09861229 1.38629436 1.60943791 1.79175947
 1.94591015 2.07944154 2.19722458 2.30258509]


## 5. Логічні операції та фільтрація

### Завдання 15
Створіть масив:

`[3, 7, 12, 18, 21, 25, 30, 34]`

За допомогою булевої маски виведіть:
1. усі числа, більші за `15`;
2. усі парні числа;
3. числа в діапазоні від `10` до `30` включно.

In [92]:
# Код студента
arr=np.array([3, 7, 12, 18, 21, 25, 30, 34])

print(arr[arr>15])
print(arr[arr%2==0])
print(arr[(arr>=10) & (arr<=30)])

 [18 21 25 30 34]
 [12 18 30 34]
 [12 18 21 25 30]


### Завдання 16
Для масиву:

`[-5, 3, -2, 8, -1, 10, 0]`

замініть усі від’ємні значення на `0`.

Не використовуйте цикл `for`.

In [96]:
# Код студента
arr=np.array([-5, 3, -2, 8, -1, 10, 0])
arr[arr<0]=0
print(arr)

[ 0  3  0  8  0 10  0]


### Завдання 17
Створіть масив випадкових цілих чисел від `0` до `100` розміром `20`.

Порахуйте:
- скільки елементів більші за `50`;
- скільки елементів менші або дорівнюють `50`.

Для відтворюваності встановіть `np.random.seed(42)`.

In [104]:
# Код студента
np.random.seed(42)
arr=np.random.randint(1, 101, 20)
print(np.sum(arr>50))
print(np.sum(arr<=50))

12
8


## 6. Зміна форми та об'єднання масивів

### Завдання 18
Створіть масив чисел від `1` до `24`.

Перетворіть його:
1. у матрицю `4 × 6`;
2. у матрицю `6 × 4`;
3. у тривимірний масив форми `2 × 3 × 4`.

Після кожного перетворення виведіть `shape`.

In [105]:
# Код студента
arr=np.arange(1,25)

print(arr.reshape(4,6))
print('\n matrix6x4',arr.reshape(6,4))
print('\n arr 2x3x4\n', arr.reshape(2,3,4))

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]
 [19 20 21 22 23 24]]

 matrix6x4 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]
 [17 18 19 20]
 [21 22 23 24]]

 arr 2x3x4
 [[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]

 [[13 14 15 16]
  [17 18 19 20]
  [21 22 23 24]]]


### Завдання 19
Створіть дві матриці:

```text
A = [[1, 2],
     [3, 4]]

B = [[5, 6],
     [7, 8]]
```

Об’єднайте їх:
1. вертикально;
2. горизонтально.

Використайте функції NumPy.

In [108]:
# Код студента
A = np.array([[1, 2],
     [3, 4]])

B = np.array([[5, 6],
     [7, 8]])

print('vertical:\n', np.vstack((A,B)))
print('horisont:\n', np.hstack((A,B)))

vertical:
 [[1 2]
 [3 4]
 [5 6]
 [7 8]]
horisont:
 [[1 2 5 6]
 [3 4 7 8]]


### Завдання 20
Створіть матрицю `3 × 4` із числами від `1` до `12`.

Перетворіть її назад в одновимірний масив двома способами:
- за допомогою `flatten()`;
- за допомогою `ravel()`.

Порівняйте результати.

In [ ]:
# Код студента
matrix=np.arange(1,13).reshape(3,4)

print('flatten', matrix.flatten())
print('ravel', matrix.ravel())
print('Однакові', np.array_equal(matrix.flatten(), matrix.ravel()))

flatten [ 1  2  3  4  5  6  7  8  9 10 11 12]
ravel [ 1  2  3  4  5  6  7  8  9 10 11 12]
Однакові True


## 7. Дії з векторами

### Завдання 21
Дано два вектори:

```text
a = [2, 4, 6]
b = [1, 3, 5]
```

Знайдіть:
- суму векторів;
- різницю векторів;
- результат множення кожного вектора на число `3`.

In [ ]:
# Код студента
a = np.array([2, 4, 6])
b = np.array([1, 3, 5])


print('sum:', a+b)

print('minus:', a-b)

print('a*3:', a*3)

print('b*3:', b*3)

sum: [ 3  7 11]
minus: [1 1 1]
a*3: [ 6 12 18]
b*3: [ 3  9 15]


### Завдання 22
Для векторів:

```text
a = [1, 2, 3]
b = [4, 5, 6]
```

Обчисліть їх **скалярний добуток** двома способами:
1. за допомогою `np.dot()`;
2. за допомогою оператора `@`.

In [ ]:
# Код студента
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

print('dot:', np.dot(a,b))
print('@:', a@b)

dot: 32
@: 32


### Завдання 23
Для вектора:

```text
v = [3, 4]
```

обчисліть його евклідову норму.

Потім нормалізуйте вектор, тобто отримайте вектор одиничної довжини.

In [ ]:
# Код студента
v = np.array([3, 4])

norm=np.linalg.norm(v)

print('норма', norm)
print('нормалізований вектор', v/norm)

 5.0
 [0.6 0.8]


### Завдання 24
Дано вектори:

```text
a = [1, 0, 0]
b = [0, 1, 0]
```

Знайдіть їх векторний добуток за допомогою `np.cross()`.

In [109]:
# Код студента
a = np.array([1, 0, 0])
b = np.array([0, 1, 0])

print("векторний добуток", np.cross(a,b))

векторний добуток [0 0 1]


### Завдання 25
Дано два вектори:

```text
a = [1, 2]
b = [2, 1]
```

Обчисліть косинус кута між ними за формулою через скалярний добуток і норми векторів.

Додатково знайдіть сам кут у градусах.

In [115]:
# Код студента
a = np.array([1, 2])
b = np.array([2, 1])

coss=np.dot(a,b)/(np.linalg.norm(a)*np.linalg.norm(b))

print(coss)
print(np.degrees(np.arccos(coss)))


0.7999999999999998
36.86989764584404


## 8. Дії з матрицями

### Завдання 26
Дано матрицю:

```text
A = [[1, 2, 3],
     [4, 5, 6]]
```

Знайдіть транспоновану матрицю двома способами:
1. за допомогою `.T`;
2. за допомогою `np.transpose()`.

In [ ]:
# Код студента
A = np.array([[1, 2, 3],
     [4, 5, 6]])

print('T:', A.T)
print('transpose:', np.transpose(A))

T: [[1 4]
 [2 5]
 [3 6]]
transpose: [[1 4]
 [2 5]
 [3 6]]


### Завдання 27
Дано матриці:

```text
A = [[1, 2],
     [3, 4]]

B = [[2, 0],
     [1, 2]]
```

Обчисліть:
1. поелементний добуток `A * B`;
2. матричний добуток `A @ B`.

Поясніть у коментарі до коду, чим відрізняються ці операції.

In [116]:
# Код студента
A=np.array([[1, 2],
     [3, 4]])

B=np.array([[2, 0],
     [1, 2]])

print('поелементний', A*B) #множення елементів з однаковими індексами
print('Матричний', A@B)#матричний це добутки елементів стовпців однієї матриці на рядки іншої тощо

поелементний [[2 0]
 [3 8]]
Матричний [[ 4  4]
 [10  8]]


### Завдання 28
Для матриці:

```text
A = [[4, 7],
     [2, 6]]
```

обчисліть:
- визначник;
- обернену матрицю.

Перевірте результат, помноживши початкову матрицю на обернену.

In [118]:
# Код студента
A = np.array([[4, 7],
     [2, 6]])

print(np.linalg.det(A))
print(np.linalg.inv(A))

10.000000000000002
[[ 0.6 -0.7]
 [-0.2  0.4]]


### Завдання 29
Розв’яжіть систему лінійних рівнянь за допомогою NumPy:

```text
2x +  y = 5
 x + 3y = 6
```

Сформуйте матрицю коефіцієнтів `A` і вектор правих частин `b`.

Використайте `np.linalg.solve()`.

In [119]:
# Код студента
mat=np.array([[2, 1],
     [1, 3]])

ans=np.array([5,6])

print(np.linalg.solve(mat, ans))

[1.8 1.4]


### Завдання 30
Створіть одиничну матрицю розміром `4 × 4`.

Перевірте властивість одиничної матриці: помножте на неї довільну матрицю `4 × 4` та порівняйте результат з початковою матрицею.

In [ ]:
# Код студента
i=np.eye(4)

a=np.arange(1,17).reshape(4,4)
result=a@i

print(i)
print(a)
print(result)
print(np.allclose(a,result))

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
[[ 1.  2.  3.  4.]
 [ 5.  6.  7.  8.]
 [ 9. 10. 11. 12.]
 [13. 14. 15. 16.]]
True


## 9. Broadcasting (операція трансляції)

### Завдання 31
Створіть матрицю:

```text
A = [[1, 2, 3],
     [4, 5, 6],
     [7, 8, 9]]
```

Додайте число `10` до кожного її елемента.

In [ ]:
# Код студента
A=np.array([[1, 2, 3],
     [4, 5, 6],
     [7, 8, 9]])

print(A+10)

[[11 12 13]
 [14 15 16]
 [17 18 19]]


### Завдання 32
До матриці:

```text
A = [[1, 2, 3],
     [4, 5, 6],
     [7, 8, 9]]
```

додайте вектор:

```text
v = [10, 20, 30]
```

Проаналізуйте, як NumPy застосував broadcasting.

In [121]:
# Код студента
A=np.array([[1, 2, 3],
     [4, 5, 6],
     [7, 8, 9]])

v=np.array([10, 20, 30])

print(A+v)#V додається до кожного рядка

[[11 22 33]
 [14 25 36]
 [17 28 39]]


### Завдання 33
Нормалізуйте **кожен стовпець** матриці:

```text
A = [[10, 20, 30],
     [20, 30, 40],
     [30, 40, 50]]
```

за формулою:

\[
z = \frac{x - \mu}{\sigma}
\]

де `μ` — середнє значення стовпця, `σ` — стандартне відхилення стовпця.

Не використовуйте цикл `for`.

In [122]:
# Код студента
A = np.array([[10, 20, 30],
     [20, 30, 40],
     [30, 40, 50]])

mean=np.mean(A, axis=0)
std=np.std(A, axis=0)

print((A-mean)/std)

[[-1.22474487 -1.22474487 -1.22474487]
 [ 0.          0.          0.        ]
 [ 1.22474487  1.22474487  1.22474487]]


## 10. Випадкові дані

### Завдання 34
Встановіть `np.random.seed(42)` та створіть:
1. 10 випадкових цілих чисел від `1` до `100`;
2. матрицю `3 × 3` випадкових чисел від `0` до `1`;
3. 1000 значень із нормального розподілу.

Для третього масиву обчисліть середнє та стандартне відхилення.

In [123]:
# Код студента
np.random.seed(42)

rndint=np.random.randint(1,101,size=10)
rndmat=np.random.random((3,3))
normval=np.random.random(size=1000)

print(rndint)
print(rndmat)
print(np.mean(normval))
print(np.std(normval))

[52 93 15 72 61 21 83 87 75 75]
[[0.86617615 0.60111501 0.70807258]
 [0.02058449 0.96990985 0.83244264]
 [0.21233911 0.18182497 0.18340451]]
0.49255598177807314
0.2917769366672639


### Завдання 35
Змоделюйте оцінки 30 студентів — випадкові цілі числа від `0` до `100`.

Визначте:
- середню оцінку;
- медіану;
- найвищу та найнижчу оцінки;
- кількість студентів, які отримали не менше `60`;
- відсоток студентів, які отримали не менше `90`.

In [67]:
# Код студента
grades=np.random.randint(0,101, size=35)

print('оцінки', grades)
print('середне', np.mean(grades))
print('максимум', np.max(grades))
print('Мінімально', min(grades))
print('Більше 60', np.sum(grades>=60))
print('Більше 90', np.sum(grades>=90))

оцінки [ 61  16  87   2  31  98  12  88  72  67  13 100  97  10  55  66  91  28
   8  66  24  97  75  41   8  78  39  24   4  10  58  97  87  78  37]
середне 52.142857142857146
максимум 100
Мінімально 2
Більше 60 17
Більше 90 6


## 11. Підсумкові завдання

### Завдання 36
Дано результати продажів трьох товарів за чотири місяці:

```text
sales = [[120, 150, 170, 160],
         [80,  90,  100, 110],
         [200, 180, 210, 230]]
```

Рядки — товари, стовпці — місяці.

Визначте:
1. загальний обсяг продажів кожного товару;
2. загальний обсяг продажів у кожному місяці;
3. товар із найбільшими сумарними продажами;
4. місяць із найбільшим загальним обсягом продажів;
5. середній обсяг продажів кожного товару.

In [134]:
# Код студента
sales = np.array([[120, 150, 170, 160],
         [80,  90,  100, 110],
         [200, 180, 210, 230]])

print(np.sum(sales, axis=1))
print(np.sum(sales, axis=0))
print(np.max(np.sum(sales, axis=1)))
print(np.max(np.sum(sales, axis=0)))
print(np.mean(sales, axis=1))

[600 380 820]
[400 420 480 500]
820
500
[150.  95. 205.]


### Завдання 37
Створіть квадратну матрицю `5 × 5` із випадкових цілих чисел від `1` до `20`.

Виконайте:
1. знайдіть суму головної діагоналі;
2. знайдіть суму побічної діагоналі;
3. знайдіть максимальний елемент кожного рядка;
4. знайдіть мінімальний елемент кожного стовпця;
5. замініть усі елементи, менші за середнє значення всієї матриці, на `0`.

In [162]:
# Код студента
np.random.seed(42)

arr=np.random.randint(1,20, 25).reshape(5,5)
print(arr)

print(sum(arr.diagonal()))
print(sum(np.fliplr(arr).diagonal()))
print(np.max(arr, axis=1))
print(np.min(arr, axis=1))

arr[arr<np.mean(arr)]=0
print(arr)

[[ 7 15 11  8  7]
 [19 11 11  4  8]
 [ 3  2 12  6  2]
 [ 1 12 12 17 10]
 [16 15 15 19 12]]
59
51
[15 19 12 17 19]
[ 7  4  2  1 12]
[[ 0 15 11  0  0]
 [19 11 11  0  0]
 [ 0  0 12  0  0]
 [ 0 12 12 17  0]
 [16 15 15 19 12]]


### Завдання 38
Дано матрицю ознак трьох об’єктів:

```text
X = [[2, 4, 6],
     [1, 3, 5],
     [5, 7, 9]]
```

Обчисліть **евклідову відстань** між:
- першим і другим рядком;
- першим і третім рядком;
- другим і третім рядком.

Використайте операції NumPy та `np.linalg.norm()`.

In [164]:
# Код студента
X = np.array([[2, 4, 6],
     [1, 3, 5],
     [5, 7, 9]])

print(np.linalg.norm(X[0]-X[1]))
print(np.linalg.norm(X[0]-X[2]))
print(np.linalg.norm(X[1]-X[2]))

1.7320508075688772
5.196152422706632
6.928203230275509


### Завдання 39
Створіть матрицю `4 × 4` із довільних цілих чисел.

Для кожного рядка знайдіть його норму та створіть нову матрицю, у якій кожен рядок нормалізований до одиничної довжини.

Спробуйте виконати завдання без циклів.

In [172]:
# Код студента
np.random.seed(42)

arr=np.random.randint(1,20, 16).reshape(4,4)
print(arr)

x1=np.linalg.norm(arr, axis=1)

arr=arr/x1[:, np.newaxis]
print(arr)

[[ 7 15 11  8]
 [ 7 19 11 11]
 [ 4  8  3  2]
 [12  6  2  1]]
[[0.32673202 0.70014004 0.51343603 0.37340802]
 [0.27414116 0.74409743 0.43079325 0.43079325]
 [0.41478068 0.82956136 0.31108551 0.20739034]
 [0.88225755 0.44112877 0.14704292 0.07352146]]


### Завдання 40
Створіть матрицю коефіцієнтів і вектор правих частин для системи:

```text
 x + 2y +  z =  9
2x +  y -  z =  8
3x -  y + 2z =  3
```

1. Розв’яжіть систему за допомогою `np.linalg.solve()`.
2. Перевірте знайдений розв’язок матричним множенням `A @ x`.
3. Порівняйте результат із вектором `b`.

In [187]:
# Код студента
a=np.array([[1,2,1],[2,1,-1],[3,-1,2]])
b=np.array([9,8,3])
x=np.linalg.solve(a,b)
print(x)
print(a@x)
if np.allclose(b, a@x):
  print("співпадає")

[ 2.22222222  3.44444444 -0.11111111]
[9. 8. 3.]
співпадає


---

## Самоперевірка

Після виконання роботи студент повинен уміти:
- створювати та перетворювати NumPy-масиви;
- використовувати індексацію та зрізи;
- виконувати векторизовані арифметичні операції;
- застосовувати агрегатні функції;
- використовувати булеві маски;
- змінювати форму та об'єднувати масиви;
- виконувати основні дії з векторами;
- виконувати основні операції з матрицями;
- застосовувати broadcasting;
- використовувати функції `numpy.linalg` для задач лінійної алгебри.
